package be.hers.info.ProjetIntegree.Services;

import be.hers.info.ProjetIntegree.DAO.DAOAddress;
import be.hers.info.ProjetIntegree.DAO.DAOBeneficiary;
import be.hers.info.ProjetIntegree.DAO.DAOCoordinator;
import be.hers.info.ProjetIntegree.DAO.DAOInterpreter;
import be.hers.info.ProjetIntegree.DTO.DTOUser;
import be.hers.info.ProjetIntegree.DTO.DTOUserAdd;
import be.hers.info.ProjetIntegree.POJO.Address;
import be.hers.info.ProjetIntegree.POJO.Beneficiary;
import be.hers.info.ProjetIntegree.POJO.Coordinator;
import be.hers.info.ProjetIntegree.POJO.Interpreter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.SQLException;
import java.util.List;

/**
 * @authors Rosman Loïs
 * @reviewer Nicolas Jean-François
 */
public class CoordinatorUsersService {

    private static final Logger logger = LoggerFactory.getLogger(CoordinatorUsersService.class);

    /**
     * @return A list containing all the beneficiaries without his password
     * @throws SQLException If an SQL error occurs with this method.
     */
    public List<DTOUser> findAllBeneficiary() throws SQLException {
        DAOBeneficiary daoBeneficiary = new DAOBeneficiary();
        return daoBeneficiary.findAllDTOBeneficiaryUsers();
    }

    /**
     * @return A list containing all the interpreters without his password, his absences, his appointmentsList,
     * and his beneficiariesList
     * @throws SQLException If an SQL error occurs with this method.
     */
    public List<DTOUser> findAllInterpreters() throws SQLException {
        DAOInterpreter daoInterpreter = new DAOInterpreter();
        return daoInterpreter.findAllDTOInterpreterUsers();
    }

    /**
     * @return A list containing all the resas without his password, his absences, his appointmentsList,
     * and his beneficiariesList
     * @throws SQLException If an SQL error occurs with this method.
     */
    public List<DTOUser> findAllResas() throws SQLException {
        DAOCoordinator daoCoordinator = new DAOCoordinator();
        return daoCoordinator.findAllDTOResaUsers();
    }

    /**
     * @return A list containing all the coordinators without his password, his absences, his appointmentsList,
     * and his beneficiariesList
     * @throws SQLException If an SQL error occurs with this method.
     */
    public List<DTOUser> findAllCoordinators() throws SQLException {
        DAOCoordinator daoCoordinator = new DAOCoordinator();
        return daoCoordinator.findAllDTOCoordinatorUsers();
    }

    /**
     * Return the number of beneficiaries in the database
     *
     * @return the number of beneficiaries in the database
     * @throws SQLException If an SQL error occurs with this method.
     */
    public int countBeneficiaries() throws SQLException {
        DAOBeneficiary daoBeneficiary = new DAOBeneficiary();
        return daoBeneficiary.countNumberBeneficiaries();
    }

    /**
     * Return the number of interpreters in the database
     *
     * @return the number of interpreters in the database
     * @throws SQLException If an SQL error occurs with this method.
     */
    public int countInterpreters() throws SQLException {
        DAOInterpreter daoInterpreter = new DAOInterpreter();
        return daoInterpreter.countNumberInterpreters();
    }

    /**
     * Return the number of resas in the database
     *
     * @return the number of resas in the database
     * @throws SQLException If an SQL error occurs with this method.
     */
    public int countResas() throws SQLException {
        DAOCoordinator daoCoordinator = new DAOCoordinator();
        return daoCoordinator.countNumberResas();
    }

    /**
     * Adds a resa or coordinator to the database.
     * Creates the Address, then the Interpreter (login generated by Oracle trigger), then the Coordinator row linked via FKnumInterpreter.
     * Reloads the Interpreter after creation to retrieve the Oracle-generated login.
     * Returns the generated login alongside the result message so the caller can send a welcome email.
     *
     * @param dtoUserAdd the data submitted from the add user form
     * @param isAdmin    true for Coordinatrice, false for Résa
     * @return an AddUserResult containing the result message and the generated login,
     *         or a failure message with null login if any step fails
     * @throws SQLException if a database error occurs during address creation
     */
    public AddUserResult addResaCoordinator(DTOUserAdd dtoUserAdd, boolean isAdmin) throws SQLException {
        String postOfficeBox = dtoUserAdd.getPostOfficeBox();
        if (postOfficeBox == null || postOfficeBox.isBlank()) {
            postOfficeBox = "-";
        }
        Address newAddress = new Address(dtoUserAdd.getPostcode(), postOfficeBox, dtoUserAdd.getLocality(), dtoUserAdd.getHamlet());
        DAOAddress daoAddress = new DAOAddress();
        daoAddress.create(newAddress);

        Interpreter newInterpreter = new Interpreter(dtoUserAdd, newAddress);
        DAOInterpreter daoInterpreter = new DAOInterpreter();
        try {
            if (!daoInterpreter.create(newInterpreter)) {
                daoAddress.delete(newAddress);
                return new AddUserResult("Ajout interprète échoué", null);
            }
        } catch (SQLException e) {
            logger.error("Erreur lors de la création de l'interprète pour le resa/coordinateur", e);
            daoAddress.delete(newAddress);
            return new AddUserResult("Ajout interprète échoué", null);
        }

        try {
            Coordinator newCoordinator = new Coordinator(dtoUserAdd, newAddress, isAdmin);
            newCoordinator.setNumInterpreter(newInterpreter.getNumInterpreter());
            DAOCoordinator daoCoordinator = new DAOCoordinator();
            if (!daoCoordinator.create(newCoordinator)) {
                daoInterpreter.delete(newInterpreter);
                daoAddress.delete(newAddress);
                return new AddUserResult("Ajout coordinatrice échoué", null);
            }
        } catch (SQLException e) {
            logger.error("Erreur lors de la création du coordinateur/resa", e);
            daoInterpreter.delete(newInterpreter);
            daoAddress.delete(newAddress);
            return new AddUserResult("Ajout coordinatrice échoué", null);
        }

        String generatedLogin = null;
        try {
            Interpreter created = daoInterpreter.find(newInterpreter.getNumInterpreter());
            if (created != null)
                generatedLogin = created.getLogin();
        } catch (SQLException e) {
            logger.warn("Impossible de récupérer le login généré pour l'interprète {}", newInterpreter.getNumInterpreter(), e);
        }

        return new AddUserResult("Ajout réussi", generatedLogin);
    }

    /**
     * Adds an interpreter to the database.
     * Creates the Address, then the Interpreter (login generated by Oracle trigger).
     * Reloads the Interpreter after creation to retrieve the Oracle-generated login.
     * Returns the generated login alongside the result message so the caller can send a welcome email.
     *
     * @param dtoUserAdd the data submitted from the add user form
     * @return an AddUserResult containing the result message and the generated login,
     *         or a failure message with null login if any step fails
     * @throws SQLException if a database error occurs during address creation
     */
    public AddUserResult addInterpreter(DTOUserAdd dtoUserAdd) throws SQLException {
        String postOfficeBox = dtoUserAdd.getPostOfficeBox();
        if (postOfficeBox == null || postOfficeBox.isBlank()) {
            postOfficeBox = "-";
        }
        Address newAddress = new Address(dtoUserAdd.getPostcode(), postOfficeBox, dtoUserAdd.getLocality(), dtoUserAdd.getHamlet());
        DAOAddress daoAddress = new DAOAddress();
        daoAddress.create(newAddress);

        Interpreter newInterpreter = new Interpreter(dtoUserAdd, newAddress);
        DAOInterpreter daoInterpreter = new DAOInterpreter();
        try {
            if (!daoInterpreter.create(newInterpreter)) {
                daoAddress.delete(newAddress);
                return new AddUserResult("Ajout interprète échoué", null);
            }
        } catch (SQLException e) {
            logger.error("Erreur lors de la création de l'interprète", e);
            daoAddress.delete(newAddress);
            return new AddUserResult("Ajout interprète échoué", null);
        }

        String generatedLogin = null;
        try {
            Interpreter created = daoInterpreter.find(newInterpreter.getNumInterpreter());
            if (created != null)
                generatedLogin = created.getLogin();
        } catch (SQLException e) {
            logger.warn("Impossible de récupérer le login généré pour l'interprète {}", newInterpreter.getNumInterpreter(), e);
        }

        return new AddUserResult("Ajout réussi", generatedLogin);
    }

    /**
     * Adds a beneficiary to the database.
     * Creates the Address, then the Beneficiary (login generated by Oracle trigger).
     * Reloads the Beneficiary after creation to retrieve the Oracle-generated login.
     * Returns the generated login alongside the result message so the caller can send a welcome email.
     *
     * @param dtoUserAdd the data submitted from the add user form
     * @return an AddUserResult containing the result message and the generated login,
     *         or a failure message with null login if any step fails
     * @throws SQLException if a database error occurs during address creation
     */
    public AddUserResult addBeneficiary(DTOUserAdd dtoUserAdd) throws SQLException {
        String postOfficeBox = dtoUserAdd.getPostOfficeBox();
        if (postOfficeBox == null || postOfficeBox.isBlank()) {
            postOfficeBox = "-";
        }
        Address newAddress = new Address(dtoUserAdd.getPostcode(), postOfficeBox, dtoUserAdd.getLocality(), dtoUserAdd.getHamlet());
        DAOAddress daoAddress = new DAOAddress();
        daoAddress.create(newAddress);

        Beneficiary newBeneficiary = new Beneficiary(dtoUserAdd, newAddress);
        DAOBeneficiary daoBeneficiary = new DAOBeneficiary();
        try {
            if (!daoBeneficiary.create(newBeneficiary)) {
                daoAddress.delete(newAddress);
                return new AddUserResult("Ajout bénéficiaire échoué", null);
            }
        } catch (SQLException e) {
            logger.error("Erreur lors de la création du bénéficiaire", e);
            daoAddress.delete(newAddress);
            return new AddUserResult("Ajout bénéficiaire échoué", null);
        }

        String generatedLogin = null;
        try {
            Beneficiary created = daoBeneficiary.find(newBeneficiary.getNumBeneficiary());
            if (created != null)
                generatedLogin = created.getLogin();
        } catch (SQLException e) {
            logger.warn("Impossible de récupérer le login généré pour le bénéficiaire {}", newBeneficiary.getNumBeneficiary(), e);
        }

        return new AddUserResult("Ajout réussi", generatedLogin);
    }

    /**
     * Holds the result of an add user operation, including the outcome message
     * and the Oracle-generated login, used to send the welcome email.
     */
    public static class AddUserResult {
        public final String message;
        public final String login;

        public AddUserResult(String message, String login) {
            this.message = message;
            this.login = login;
        }
    }
}
