package be.hers.info.ProjetIntegree.DAO;

import be.hers.info.ProjetIntegree.POJO.*;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Vatafu Jean
 * @reviewer Nicolas Jean-François, Louis Halet
 */

public class DAOAbsence {

    /**
     * Searches for an Absence by its numAbsence.
     * The TimeSlotPunctual is loaded via DAOTimeSlotPunctual
     * @param objectToSearchInDB the numAbsence to search for
     * @return The Absence if found, null otherwise
     * @throws SQLException In case of any SQL problems encountered with this method
     * @throws BadStatusException In case the status of the absence found does not match 'en attente',
     * 'acceptee' or 'refusee'
     */
    public Absence find(int objectToSearchInDB) throws SQLException, BadStatusException {
        Connection connect = ConnectionOracle.getInstance();
        Absence absence = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;

        String query = "SELECT status, reasons, privateReason, FKTimeSlotBase, FKTimeSlotPunctual " +
                "FROM Absence " +
                "WHERE numAbsence = ?";

        try {
            preparedStatement = connect.prepareStatement(query);
            preparedStatement.setInt(1, objectToSearchInDB);

            resultSet = preparedStatement.executeQuery();

            if(resultSet.next()) {
                TimeSlot timeSlot = null;

                if(resultSet.getObject("FKTimeSlotBase") != null) {
                    DAOTimeSlotBase daoTimeSlotBase = new DAOTimeSlotBase();
                    timeSlot = daoTimeSlotBase.find(resultSet.getInt("FKTimeSlotBase"));
                } else {
                    DAOTimeSlotPunctual daoTimeSlotPunctual = new DAOTimeSlotPunctual();
                    timeSlot = daoTimeSlotPunctual.find(resultSet.getInt("FKTimeSlotPunctual"));
                }

                absence = new Absence(objectToSearchInDB, resultSet.getString("status"), timeSlot,
                        resultSet.getString("reasons"), resultSet.getBoolean("privateReason"));
            }
        } finally {
            closeStatementAndResultSet(preparedStatement, resultSet);
        }
        return absence;
    }

    /**
     * Creates a list containing all the Absence in the Absence table
     * For each Absence, the TimeSlotPunctual is loaded via DAOTimeSlotPunctual
     * @return A list containing all the Absence, or an empty list if the table is empty
     * @throws SQLException In case of any SQL problems encountered with this method
     * @throws BadStatusException In case the status of the absence found does not match 'en attente',
     *      * 'acceptee' or 'refusee'
     */
    public List<Absence> findAll() throws SQLException, BadStatusException {
        Connection connect = ConnectionOracle.getInstance();
        List<Absence> absenceList = new ArrayList<Absence>();
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;

        String query = "SELECT numAbsence, status, reasons, privateReason, FKTimeSlotBase, FKTimeSlotPunctual " +
                "FROM Absence";

        try {
            preparedStatement = connect.prepareStatement(query);
            resultSet = preparedStatement.executeQuery();

            DAOTimeSlotPunctual daoTimeSlotPunctual = new DAOTimeSlotPunctual();
            DAOTimeSlotBase daoTimeSlotBase = new DAOTimeSlotBase();
            TimeSlot timeSlot = null;

            while(resultSet.next()) {
                if(resultSet.getObject("FKTimeSlotBase") != null) {
                    timeSlot = daoTimeSlotBase.find(resultSet.getInt("FKTimeSlotBase"));
                } else {
                    timeSlot = daoTimeSlotPunctual.find(resultSet.getInt("FKTimeSlotPunctual"));
                }

                Absence absence = new Absence(resultSet.getInt("numAbsence"), resultSet.getString("status"),
                        timeSlot, resultSet.getString("reasons"), resultSet.getBoolean("privateReason"));

                absenceList.add(absence);
            }
        } finally {
            closeStatementAndResultSet(preparedStatement, resultSet);
        }
        return absenceList;
    }

    /**
     * Adds the Absence passed as a parameter to the Absence table,
     * then inserts its Interpreter via an additinal parameter
     * The numAbsence is auto-generated by Oracle
     * Precondition: the Absence passed as a parameter cannot be null
     * Precondition: the TimeSlotPunctual of the Absence must already exist in the database
     * Precondition: the Interpreter must already exist in the database
     * @param objectToInsertInDB the Absence to be inserted into the table
     * @param otherObjectID the id of the Interpreter to which this Absence belongs to
     * @return true if the Absence is successfully inserted, false otherwise
     * @throws SQLException In case of any SQL problems encountered with this method
     * @throws IllegalArgumentException If otherObjectID is negative
     */
    public boolean create(Absence objectToInsertInDB, int otherObjectID) throws SQLException, IllegalArgumentException {
        Connection connect = ConnectionOracle.getInstance();
        boolean created = false;
        PreparedStatement preparedStatement = null;

        if(otherObjectID < 0) {
            throw new IllegalArgumentException("[DAOAbsence] L'id de l'interprète ne peut pas être négatif.");
        }

        String query = "INSERT INTO Absence(status, reasons, privateReason, FKTimeSlotBase, FKTimeSlotPunctual, FKnumInterpreter) " +
                "VALUES (?, ?, ?, ?, ?, ?)";

        try {
            preparedStatement = connect.prepareStatement(query);

            preparedStatement.setString(1, objectToInsertInDB.getStatus());
            preparedStatement.setString(2, objectToInsertInDB.getReason());
            preparedStatement.setBoolean(3, objectToInsertInDB.isPrivateReason());

            if(objectToInsertInDB.getTimeSlot() instanceof TimeSlotBase) {
                preparedStatement.setInt(4, objectToInsertInDB.getTimeSlot().getNumTimeSlot());
                preparedStatement.setNull(5, java.sql.Types.INTEGER);
            } else {
                preparedStatement.setNull(4, java.sql.Types.INTEGER);
                preparedStatement.setInt(5, objectToInsertInDB.getTimeSlot().getNumTimeSlot());
            }

            preparedStatement.setInt(6, otherObjectID);

            if(preparedStatement.executeUpdate() > 0) {
                created = true;
            }
        } finally {
            closeStatement(preparedStatement);
        }
        return created;
    }

    /**
     * Updates status Absence fields in the table except its id
     * Precondition: the Absence passed as a parameter cannot be null
     * @param objectToUpdateInDB the Absence to update
     * @return true if the Absence was successfully updated, false otherwise
     * @throws SQLException In case of any SQL problems encountered with this method
     */
    public boolean update(Absence objectToUpdateInDB) throws SQLException {
        Connection connect = ConnectionOracle.getInstance();
        boolean updated = false;
        PreparedStatement preparedStatement = null;

        String query = "UPDATE Absence " +
                "SET status = ?, reasons = ?, privateReason = ?, FKTimeSlotBase = ?, FKTimeSlotPunctual = ? "+
                "WHERE numAbsence = ?";

        try {
            preparedStatement = connect.prepareStatement(query);

            preparedStatement.setString(1, objectToUpdateInDB.getStatus());
            preparedStatement.setString(2, objectToUpdateInDB.getReason());
            preparedStatement.setBoolean(3, objectToUpdateInDB.isPrivateReason());

            if(objectToUpdateInDB.getTimeSlot() instanceof TimeSlotBase) {
                preparedStatement.setInt(4, objectToUpdateInDB.getTimeSlot().getNumTimeSlot());
                preparedStatement.setNull(5, java.sql.Types.INTEGER);
            } else {
                preparedStatement.setNull(4, java.sql.Types.INTEGER);
                preparedStatement.setInt(5, objectToUpdateInDB.getTimeSlot().getNumTimeSlot());
            }

            preparedStatement.setInt(6, objectToUpdateInDB.getNumAbsence());

            if(preparedStatement.executeUpdate() > 0) {
                updated = true;
            }
        } finally {
            closeStatement(preparedStatement);
        }
        return updated;
    }

    /**
     * Deletes the Absence whose numAbsence matches the numAbsence
     * Precondition: the Absence passed as a parameter cannot be null
     * @param objectToDeleteFormDB the Absence to be deleted from the table
     * @return true if the Absence was successfully deleted, false otherwise
     * @throws SQLException In case of any SQL problems encountered with this method
     */
    public boolean delete(Absence objectToDeleteFormDB) throws SQLException {
        Connection connect = ConnectionOracle.getInstance();
        boolean isDeleted = false;
        PreparedStatement preparedStatement = null;

        String query = "DELETE FROM Absence " +
                "WHERE numAbsence = ?";

        try {
            preparedStatement = connect.prepareStatement(query);

            preparedStatement.setInt(1, objectToDeleteFormDB.getNumAbsence());

            if(preparedStatement.executeUpdate() > 0) {
                isDeleted = true;
            }
        } finally {
            closeStatement(preparedStatement);
        }
        return isDeleted;
    }

    /**
     * Close the PreparedStatement given in param
     * @param preparedStatement the statement to close
     */
    public void closeStatement(PreparedStatement preparedStatement) {
        if (preparedStatement != null) {
            try {
                preparedStatement.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * Close the ResultSet and the PrepareStatement given in param
     * @param preparedStatement the statement to close
     * @param resultSet the ResutlSet to close
     */
    public void closeStatementAndResultSet(PreparedStatement preparedStatement, ResultSet resultSet) {
        if(resultSet != null) {
            try {
                resultSet.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

        closeStatement(preparedStatement);
    }
}
