package be.hers.info.ProjetIntegree.DAO;

import be.hers.info.ProjetIntegree.POJO.Absence;
import be.hers.info.ProjetIntegree.POJO.BadStatusException;
import be.hers.info.ProjetIntegree.POJO.Interpreter;
import be.hers.info.ProjetIntegree.POJO.TimeSlotPunctual;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Vatafu Jean
 * @reviewer Nicolas Jean-François, Louis Halet
 */

public class DAOAbsence {

    /**
     * Searches for an Absence by its numAbsence.
     * The TimeSlotPunctual is loaded via DAOTimeSlotPunctual
     * @param objectToSearchInDB the numAbsence to search for
     * @return The Absence if found, null otherwise
     * @throws SQLException In case of any SQL problems encountered with this method
     * @throws BadStatusException In case the status of the absence found does not match 'en attente',
     * 'acceptee' or 'refusee'
     */
    public Absence find(int objectToSearchInDB) throws SQLException, BadStatusException {
        Connection connect = ConnectionOracle.getInstance();
        Absence absence = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;

        String query = "SELECT status, FKTimeSlotPunctual " +
                "FROM Absence " +
                "WHERE numAbsence = ?";

        try {
            preparedStatement = connect.prepareStatement(query);
            preparedStatement.setInt(1, objectToSearchInDB);

            resultSet = preparedStatement.executeQuery();

            if(resultSet.next()) {
                DAOTimeSlotPunctual daoTimeSlotPunctual = new DAOTimeSlotPunctual();
                TimeSlotPunctual timeSlotPunctual = daoTimeSlotPunctual.find(resultSet.getInt("FKTimeSlotPunctual"));

                absence = new Absence(objectToSearchInDB, resultSet.getString("status"),timeSlotPunctual);
            }
        } finally {
            closeStatementAndResultSet(preparedStatement, resultSet);
        }
        return absence;
    }

    /**
     * Creates a list containing all the Absence in the Absence table
     * For each Absence, the TimeSlotPunctual is loaded via DAOTimeSlotPunctual
     * @return A list containing all the Absence, or an empty list if the table is empty
     * @throws SQLException In case of any SQL problems encountered with this method
     * @throws BadStatusException In case the status of the absence found does not match 'en attente',
     *      * 'acceptee' or 'refusee'
     */
    public List<Absence> findAll() throws SQLException, BadStatusException {
        Connection connect = ConnectionOracle.getInstance();
        List<Absence> absenceList = new ArrayList<Absence>();
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;

        String query = "SELECT numAbsence, status, FKTimeSlotPunctual " +
                "FROM Absence";

        try {
            preparedStatement = connect.prepareStatement(query);
            resultSet = preparedStatement.executeQuery();

            DAOTimeSlotPunctual daoTimeSlotPunctual = new DAOTimeSlotPunctual();

            while(resultSet.next()) {
                Absence absence = new Absence(resultSet.getInt("numAbsence"), resultSet.getString("status"),
                        daoTimeSlotPunctual.find(resultSet.getInt("FKTimeSlotPunctual")));

                absenceList.add(absence);
            }
        } finally {
            closeStatementAndResultSet(preparedStatement, resultSet);
        }
        return absenceList;
    }



    /**
     * Adds the Absence passed as a parameter to the Absence table,
     * then inserts its Interpreter via an additinal parameter
     * The numAbsence is auto-generated by Oracle
     * Precondition: the Absence passed as a parameter cannot be null
     * Precondition: the TimeSlotPunctual of the Absence must already exist in the database
     * Precondition: the Interpreter must already exist in the database
     * @param objectToInsertInDB the Absence to be inserted into the table
     * @param otherObjectID the id of the Interpreter to which this Absence belongs to
     * @return true if the Absence is successfully inserted, false otherwise
     * @throws SQLException In case of any SQL problems encountered with this method
     * @throws IllegalArgumentException If otherObjectID is negative
     */
    public boolean create(Absence objectToInsertInDB, int otherObjectID) throws SQLException, IllegalArgumentException {
        Connection connect = ConnectionOracle.getInstance();
        boolean created = false;
        PreparedStatement preparedStatement = null;

        if(otherObjectID < 0) {
            throw new IllegalArgumentException("[DAOAbsence] L'id de l'interprète ne peut pas être négatif.");
        }

        String query = "INSERT INTO Absence(status, FKTimeSlotPunctual, FKnumInterpreter) " +
                "VALUES ( ?, ?, ?)";

        try {
            preparedStatement = connect.prepareStatement(query);

            preparedStatement.setString(1, objectToInsertInDB.getStatus());
            preparedStatement.setInt(2, objectToInsertInDB.getTimeSlotPunctual().getNumTimeSlot());
            preparedStatement.setInt(3, otherObjectID);

            if(preparedStatement.executeUpdate() > 0) {
                created = true;
            }
        } finally {
            closeStatement(preparedStatement);
        }

        return created;
    }

    /**
     * Updates all Absence fields in the table except its id
     * The Address is updated via its numAddress (the Address itself is not updated here).
     * Precondition: the Interpreter passed as a parameter cannot be null.
     * @param objectToUpdateInDB the Interpreter containing the numInterpreter and the fields to update.
     * @return true if the Interpreter was successfully updated, false otherwise.
     * @throws SQLException In case of any SQL problems encountered with this method.
     */


    // TODO : Don't know if i should update the TimeSlotPunctual? Also the interpreter ? So many questions so little reponses
    public boolean update(Absence objectToUpdateInDB) throws SQLException {
        Connection connect = ConnectionOracle.getInstance();
        boolean updated = false;
        PreparedStatement preparedStatement = null;

        String query = "UPDATE Absence " +
                "SET status = ?, FKTimeSlotPunctual = ? " +
                "WHERE numAbsence = ?";

        try {
            preparedStatement = connect.prepareStatement(query);
            preparedStatement.setString(1, objectToUpdateInDB.getStatus());
            preparedStatement.setInt(2, objectToUpdateInDB.getTimeSlotPunctual().getNumTimeSlot());
            preparedStatement.setInt(3, objectToUpdateInDB.getNumAbsence());

            if(preparedStatement.executeUpdate() > 0) {
                updated = true;
            }
        } finally {
            closeStatement(preparedStatement);
        }
        return updated;
    }

    public boolean delete(Absence objectToDeleteFormDB) throws SQLException {
        Connection connect = ConnectionOracle.getInstance();
        boolean isDeleted = false;
        PreparedStatement preparedStatement = null;

        String query = "DELETE FROM Absence " +
                "WHERE numAbsence = ?";

        try {
            preparedStatement = connect.prepareStatement(query);

            preparedStatement.setInt(1, objectToDeleteFormDB.getNumAbsence());

            if(preparedStatement.executeUpdate() > 0) {
                isDeleted = true;
            }
        } finally {
            closeStatement(preparedStatement);
        }
        return isDeleted;
    }

    /**
     * Close the PreparedStatement given in param
     * @param preparedStatement the statement to close
     */
    public void closeStatement(PreparedStatement preparedStatement) {
        if (preparedStatement != null) {
            try {
                preparedStatement.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * Close the ResultSet and the PrepareStatement given in param
     * @param preparedStatement the statement to close
     * @param resultSet the ResutlSet to close
     */
    public void closeStatementAndResultSet(PreparedStatement preparedStatement, ResultSet resultSet) {
        closeStatement(preparedStatement);

        if(resultSet != null) {
            try {
                resultSet.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
}
