package be.hers.info.ProjetIntegree.DAO;

import be.hers.info.ProjetIntegree.POJO.Address;
import be.hers.info.ProjetIntegree.POJO.Interpreter;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Wellinger Chloé
 * @reviewer Nicolas Jean-Francois, Halet Louis
 */

public class DAOInterpreter extends DAO<Interpreter> {

    /**
     * Searches for an Interpreter by its numInterpreter.
     * The Address is loaded eagerly via DAOAddress.
     * Absences, Skills, Appointments and Beneficiaries are not loaded (lazy loading).
     * @param idToSearchInDB the numInterpreter of the Interpreter to search for.
     * @return The Interpreter if found, null otherwise.
     * @throws SQLException In case of any SQL problems encountered with this method.
     */
    @Override
    public Interpreter find(int idToSearchInDB) throws SQLException {
        PreparedStatement prStat = null;
        ResultSet rs = null;
        Interpreter interpreterFind = null;

        String query = "SELECT * " +
                "FROM Interpreter " +
                "WHERE numInterpreter = ?";

        try {
            prStat = connect.prepareStatement(query);
            prStat.setInt(1, idToSearchInDB);
            rs = prStat.executeQuery();

            if(rs.next()) {
                DAOAddress daoAddress = new DAOAddress();
                Address address = daoAddress.find(rs.getInt("numAdress"));

                interpreterFind = new Interpreter(
                        rs.getInt("numInterpreter"),
                        rs.getString("lastName"),
                        rs.getString("firstName"),
                        rs.getString("emailAddress"),
                        rs.getString("phoneNumber"),
                        rs.getInt("weeklyWorkHours"),
                        address
                );
            }
        } finally {
            if (rs != null) {
                try {
                    rs.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
            if (prStat != null) {
                try {
                    prStat.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }
        return interpreterFind;
    }

    /**
     * Creates a list containing all the Interpreters in the table.
     * For each Interpreter, the Address is loaded eagerly via DAOAddress.
     * Absences, Skills, Appointments and Beneficiaries are not loaded (lazy loading).
     * @return a list containing all the Interpreters, or an empty list if the table is empty.
     * @throws SQLException In case of any SQL problems encountered with this method.
     */
    @Override
    public List<Interpreter> findAll() throws SQLException {
        List<Interpreter> interpreterList = new ArrayList<>();
        PreparedStatement prStat = null;
        ResultSet rs = null;

        String query = "SELECT * " +
                "FROM Interpreter";

        try {
            prStat = connect.prepareStatement(query);
            rs = prStat.executeQuery();

            while(rs.next()) {
                DAOAddress daoAddress = new DAOAddress();
                Address address = daoAddress.find(rs.getInt("numAdress"));

                Interpreter interpreterFind = new Interpreter(
                        rs.getInt("numInterpreter"),
                        rs.getString("lastName"),
                        rs.getString("firstName"),
                        rs.getString("emailAddress"),
                        rs.getString("phoneNumber"),
                        rs.getInt("weeklyWorkHours"),
                        address
                );
                interpreterList.add(interpreterFind);
            }
        } finally {
            if (rs != null) {
                try {
                    rs.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
            if (prStat != null) {
                try {
                    prStat.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }
        return interpreterList;
    }

    /**
     * Adds the Interpreter passed as a parameter to the table.
     * The numInterpreter is auto-generated by Oracle,
     * it must therefore not be included in the INSERT statement.
     * Precondition: the Interpreter passed as a parameter cannot be null.
     * Precondition: the Address of the Interpreter must already exist in the database.
     * @param objectToInsertInDB the Interpreter to be inserted into the table.
     * @return true if the Interpreter was successfully inserted, false otherwise.
     * @throws SQLException In case of any SQL problems encountered with this method.
     */
    @Override
    public boolean create(Interpreter objectToInsertInDB) throws SQLException {
        boolean isInserted = false;
        PreparedStatement prStat = null;

        String query = "INSERT INTO Interpreter (lastName, firstName, emailAddress, " +
                "phoneNumber, weeklyWorkHours, numAddress) " +
                "VALUES (?, ?, ?, ?, ?, ?)";

        try {
            prStat = connect.prepareStatement(query);
            prStat.setString(1, objectToInsertInDB.getLastName());
            prStat.setString(2, objectToInsertInDB.getFirstName());
            prStat.setString(3, objectToInsertInDB.getEmail());
            prStat.setString(4, objectToInsertInDB.getPhoneNumber());
            prStat.setInt(5, objectToInsertInDB.getWeeklyWorkHours());
            prStat.setInt(6, objectToInsertInDB.getAddress().getNumAddress());

            int nbLinesInsert = prStat.executeUpdate();
            if(nbLinesInsert > 0) {
                isInserted = true;
            }
        } finally {
            if (prStat != null) {
                try {
                    prStat.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }
        return isInserted;
    }

    /**
     * Updates all Interpreter fields in the table (except its numInterpreter)
     * The Address is updated via its numAddress (the Address itself is not updated here).
     * Precondition: the Interpreter passed as a parameter cannot be null.
     * @param objectToUpdateInDB the Interpreter containing the numInterpreter and the fields to update.
     * @return true if the Interpreter was successfully updated, false otherwise.
     * @throws SQLException In case of any SQL problems encountered with this method.
     */
    @Override
    public boolean update(Interpreter objectToUpdateInDB) throws SQLException {
        boolean isUpdated = false;
        PreparedStatement prStat = null;

        String query = "UPDATE Interpreter " +
                "SET lastName = ?, firstName = ?, emailAddress = ?, phoneNumber = ?, weeklyWorkHours = ?, numAddress = ?" +
                " WHERE numInterpreter = ?";

        try {
            prStat = connect.prepareStatement(query);
            prStat.setString(1, objectToUpdateInDB.getLastName());
            prStat.setString(2, objectToUpdateInDB.getFirstName());
            prStat.setString(3, objectToUpdateInDB.getEmail());
            prStat.setString(4, objectToUpdateInDB.getPhoneNumber());
            prStat.setInt(5, objectToUpdateInDB.getWeeklyWorkHours());
            prStat.setInt(6, objectToUpdateInDB.getAddress().getNumAddress());
            prStat.setInt(7, objectToUpdateInDB.getNumInterpreter());

            int nbLinesUpdate = prStat.executeUpdate();
            if(nbLinesUpdate > 0) {
                isUpdated = true;
            }
        } finally {
            if (prStat != null) {
                try {
                    prStat.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }
        return isUpdated;
    }

    /**
     * Deletes the Interpreter whose numInterpreter matches the numInterpreter
     * of the Interpreter passed as a parameter.
     * Precondition: the Interpreter passed as a parameter cannot be null.
     * @param objectToDeleteFormDB the Interpreter to be deleted from the table.
     * @return true if the Interpreter was successfully deleted, false otherwise.
     * @throws SQLException In case of any SQL problems encountered with this method.
     */
    @Override
    public boolean delete(Interpreter objectToDeleteFormDB) throws SQLException {
        boolean isDeleted = false;
        PreparedStatement prStat = null;

        String query = "DELETE FROM Interpreter " +
                "WHERE numInterpreter = ?";

        try {
            prStat = connect.prepareStatement(query);
            prStat.setInt(1, objectToDeleteFormDB.getNumInterpreter());

            int nbLinesDelete = prStat.executeUpdate();
            if(nbLinesDelete > 0) {
                isDeleted = true;
            }
        } finally {
            if (prStat != null) {
                try {
                    prStat.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }
        return isDeleted;
    }
}
