package be.hers.info.ProjetIntegree.DAO;

import be.hers.info.ProjetIntegree.POJO.AcademicSkill;
import be.hers.info.ProjetIntegree.POJO.Address;
import be.hers.info.ProjetIntegree.POJO.Interpreter;

import be.hers.info.ProjetIntegree.POJO.ProfessionalSkill;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleTypes;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Wellinger Chloé
 * @reviewer Nicolas Jean-Francois, Halet Louis
 */

public class DAOInterpreter extends DAO<Interpreter> {

    /**
     * Searches for an Interpreter by its numInterpreter.
     * The Address is loaded eagerly via DAOAddress.
     * Absences, Skills, Appointments and Beneficiaries are not loaded (lazy loading).
     * @param idToSearchInDB the numInterpreter of the Interpreter to search for.
     * @return The Interpreter if found, null otherwise.
     * @throws SQLException In case of any SQL problems encountered with this method.
     */
    @Override
    public Interpreter find(int idToSearchInDB) throws SQLException {
        PreparedStatement prStat = null;
        ResultSet rs = null;
        Interpreter interpreterFind = null;

        String query = "SELECT numInterpreter, login, password, lastName, firstName, emailAddress, phoneNumber, weeklyWorkHours, FKAddress " +
                "FROM Interpreter " +
                "WHERE numInterpreter = ?";

        try {
            prStat = connect.prepareStatement(query);
            prStat.setInt(1, idToSearchInDB);
            rs = prStat.executeQuery();

            if(rs.next()) {
                DAOAddress daoAddress = new DAOAddress();
                Address addressInterpreter = daoAddress.find(rs.getInt("FKAddress"));

                interpreterFind = new Interpreter(
                        rs.getInt("numInterpreter"),
                        rs.getString("login"),
                        rs.getString("password"),
                        rs.getString("lastName"),
                        rs.getString("firstName"),
                        rs.getString("emailAddress"),
                        rs.getString("phoneNumber"),
                        rs.getInt("weeklyWorkHours"),
                        addressInterpreter
                );
            }
        } finally {
            closeStatementAndResultSet(prStat, rs);
        }
        return interpreterFind;
    }

    /**
     * Creates a list containing all the Interpreters in the table.
     * For each Interpreter, the Address is loaded eagerly via DAOAddress.
     * Absences, Skills, Appointments and Beneficiaries are not loaded (lazy loading).
     * @return a list containing all the Interpreters, or an empty list if the table is empty.
     * @throws SQLException In case of any SQL problems encountered with this method.
     */
    @Override
    public List<Interpreter> findAll() throws SQLException {
        List<Interpreter> interpreterList = new ArrayList<>();
        PreparedStatement prStat = null;
        ResultSet rs = null;

        String query = "SELECT numInterpreter, login, password, lastName, firstName, emailAddress, phoneNumber, weeklyWorkHours, FKAddress " +
                "FROM Interpreter";

        try {
            prStat = connect.prepareStatement(query);
            rs = prStat.executeQuery();

            while(rs.next()) {
                DAOAddress daoAddress = new DAOAddress();
                Address addressInterpreter = daoAddress.find(rs.getInt("FKAddress"));

                Interpreter interpreterFind = new Interpreter(
                        rs.getInt("numInterpreter"),
                        rs.getString("login"),
                        rs.getString("password"),
                        rs.getString("lastName"),
                        rs.getString("firstName"),
                        rs.getString("emailAddress"),
                        rs.getString("phoneNumber"),
                        rs.getInt("weeklyWorkHours"),
                        addressInterpreter
                );
                interpreterList.add(interpreterFind);
            }
        } finally {
            closeStatementAndResultSet(prStat, rs);
        }
        return interpreterList;
    }

    /**
     * Adds the Interpreter passed as a parameter to the table,
     * then inserts its professional and academic skills into the junction tables
     * ProfessionalSkillInterpreter and AcademicSkillInterpreter.
     * The numInterpreter is auto-generated by Oracle and retrieved via RETURNING INTO.
     * It must therefore not be included in the INSERT statement.
     * Precondition: the Interpreter passed as a parameter cannot be null.
     * Precondition: the Address of the Interpreter must already exist in the database.
     * Precondition: all ProfessionalSkill in the list must already exist in the database.
     * Precondition: all AcademicSkill in the list must already exist in the database.
     * @param objectToInsertInDB the Interpreter to be inserted into the table.
     * @return true if the Interpreter and all its skills were successfully inserted, false otherwise.
     * @throws SQLException In case of any SQL problems encountered with this method.
     */
    @Override
    public boolean create(Interpreter objectToInsertInDB) throws SQLException {
        boolean isInserted = false;
        OraclePreparedStatement prStatInterpreter = null;
        PreparedStatement prStatProfSkill = null;
        PreparedStatement prStatAcadSkill = null;
        ResultSet generateID = null;

        String queryInterpreter = "INSERT INTO Interpreter (login, password, lastName, firstName, emailAddress, " +
                "phoneNumber, weeklyWorkHours, FKAddress) " +
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?) " +
                "RETURNING numInterpreter INTO ?";

        String queryProfSkill = "INSERT INTO ProfessionalSkillInterpreter (numProfessionalSkill, numInterpreter) " +
                "VALUES (?, ?)";

        String queryAcadSkill = "INSERT INTO AcademicSkillInterpreter (numAcademicSkill, numInterpreter) " +
                "VALUES (?, ?)";

        try {
            prStatInterpreter = (OraclePreparedStatement) connect.prepareStatement(queryInterpreter);
            prStatInterpreter.setString(1, objectToInsertInDB.getLogin());
            prStatInterpreter.setString(2, objectToInsertInDB.getPassword());
            prStatInterpreter.setString(3, objectToInsertInDB.getLastName());
            prStatInterpreter.setString(4, objectToInsertInDB.getFirstName());
            prStatInterpreter.setString(5, objectToInsertInDB.getEmailAddress());
            prStatInterpreter.setString(6, objectToInsertInDB.getPhoneNumber());
            prStatInterpreter.setInt(7, objectToInsertInDB.getWeeklyWorkHours());
            prStatInterpreter.setInt(8, objectToInsertInDB.getAddress().getNumAddress());
            prStatInterpreter.registerReturnParameter(9, OracleTypes.INTEGER);

            int nbLinesInsert = prStatInterpreter.executeUpdate();

            if(nbLinesInsert > 0) {
                // Retrieve the generated number
                generateID = prStatInterpreter.getReturnResultSet();
                if(!generateID.next()) {
                    throw new SQLException("[DAOInterpreter] Impossible de récupérer le numInterpreter généré.");
                }
                int numInterpreterGenerated = generateID.getInt(1);
                objectToInsertInDB.setNumInterpreter(numInterpreterGenerated);

                // Insert the professional skills
                if (objectToInsertInDB.getProfessionalSkillsList() != null && !objectToInsertInDB.getProfessionalSkillsList().isEmpty()) {
                    prStatProfSkill = connect.prepareStatement(queryProfSkill);
                    for (ProfessionalSkill ps : objectToInsertInDB.getProfessionalSkillsList()) {
                        prStatProfSkill.setInt(1, ps.getNumProfessionalSkill());
                        prStatProfSkill.setInt(2, numInterpreterGenerated);
                        prStatProfSkill.executeUpdate();
                    }
                }

                // Insert the academic skills
                if (objectToInsertInDB.getAcademicSkillsList() != null && !objectToInsertInDB.getAcademicSkillsList().isEmpty()) {
                    prStatAcadSkill = connect.prepareStatement(queryAcadSkill);
                    for (AcademicSkill ps : objectToInsertInDB.getAcademicSkillsList()) {
                        prStatAcadSkill.setInt(1, ps.getNumAcademicSkill());
                        prStatAcadSkill.setInt(2, numInterpreterGenerated);
                        prStatAcadSkill.executeUpdate();
                    }
                }
                isInserted = true;
            }
        } finally {
            closeStatementAndResultSet(prStatInterpreter, generateID);
            closeStatement(prStatProfSkill);
            closeStatement(prStatAcadSkill);
        }
        return isInserted;
    }

    /**
     * Updates all Interpreter fields in the table (except its numInterpreter)
     * The Address is updated via its numAddress (the Address itself is not updated here).
     * Precondition: the Interpreter passed as a parameter cannot be null.
     * @param objectToUpdateInDB the Interpreter containing the numInterpreter and the fields to update.
     * @return true if the Interpreter was successfully updated, false otherwise.
     * @throws SQLException In case of any SQL problems encountered with this method.
     */
    @Override
    public boolean update(Interpreter objectToUpdateInDB) throws SQLException {
        boolean isUpdated = false;
        PreparedStatement prStat = null;

        String query = "UPDATE Interpreter " +
                "SET login = ?, password = ?, lastName = ?, firstName = ?, emailAddress = ?, phoneNumber = ?, weeklyWorkHours = ?, FKAddress = ?" +
                " WHERE numInterpreter = ?";

        try {
            prStat = connect.prepareStatement(query);
            prStat.setString(1, objectToUpdateInDB.getLogin());
            prStat.setString(2, objectToUpdateInDB.getPassword());
            prStat.setString(3, objectToUpdateInDB.getLastName());
            prStat.setString(4, objectToUpdateInDB.getFirstName());
            prStat.setString(5, objectToUpdateInDB.getEmailAddress());
            prStat.setString(6, objectToUpdateInDB.getPhoneNumber());
            prStat.setInt(7, objectToUpdateInDB.getWeeklyWorkHours());
            prStat.setInt(8, objectToUpdateInDB.getAddress().getNumAddress());
            prStat.setInt(9, objectToUpdateInDB.getNumInterpreter());

            int nbLinesUpdate = prStat.executeUpdate();
            if(nbLinesUpdate > 0) {
                isUpdated = true;
            }
        } finally {
            closeStatement(prStat);
        }
        return isUpdated;
    }

    /**
     * Deletes the Interpreter whose numInterpreter matches the numInterpreter
     * of the Interpreter passed as a parameter.
     * Precondition: the Interpreter passed as a parameter cannot be null.
     * @param objectToDeleteFormDB the Interpreter to be deleted from the table.
     * @return true if the Interpreter was successfully deleted, false otherwise.
     * @throws SQLException In case of any SQL problems encountered with this method.
     */
    @Override
    public boolean delete(Interpreter objectToDeleteFormDB) throws SQLException {
        boolean isDeleted = false;
        PreparedStatement prStat = null;

        String query = "DELETE FROM Interpreter " +
                "WHERE numInterpreter = ?";

        try {
            prStat = connect.prepareStatement(query);
            prStat.setInt(1, objectToDeleteFormDB.getNumInterpreter());

            int nbLinesDelete = prStat.executeUpdate();
            if(nbLinesDelete > 0) {
                isDeleted = true;
            }
        } finally {
            closeStatement(prStat);
        }
        return isDeleted;
    }
}
